services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  api:
    build:
      context: ./api
      # ¡Aquí está la magia! Le decimos que use el Dockerfile de desarrollo.
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - db
    env_file:
      - ./api/.env
    volumes:
      # Sincroniza tu código local con el contenedor para live-reloading.
      - ./api:/app
      # Evita conflictos con node_modules.
      - /app/node_modules
    command: npm run dev
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

volumes:
  postgres_data:
