GET http://localhost:4000/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YmZkNzFiMy0xMjY2LTQwYWMtODU2MS0xYjZkMDdiNzY1YjAiLCJjbGllbnRJZCI6IjBmNTg5MWQyLWE4MWItNDg0NC1hODZjLTAzOWRkN2Y3MjE2ZCIsInVzZXJuYW1lIjoiMDAyODEiLCJpYXQiOjE3NTIwNzMzMTAsImV4cCI6MTc1MjY3ODExMH0.8AXF5YAGyyULIwufIc86-oRBzM-z8hiZHcAQif_DlY8
Content-Type: application/json
