GET http://localhost:4000/api/products/4fc23118-4110-4c01-8007-c73892d21241
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YjdhZjExOC1kM2M3LTQ2YmUtYmE2OC1kNDBjNmY0ZTFlZjEiLCJjbGllbnRJZCI6ImNjYTM5MWJlLTE1ZTktNDJhYi1hOTAwLTUwMWUwNjM4ZjA5NiIsInVzZXJuYW1lIjoiMDAyODEiLCJpYXQiOjE3NTI1MDI3NjYsImV4cCI6MTc1MzEwNzU2Nn0.l-dLDSJUklFtPjmDk8DZUEPKVXLpdL0eWWVev4fwvXo
Accept: application/json
