# api/Dockerfile.dev

FROM node:22.17-bookworm-slim
WORKDIR /app

# Copia solo package.json para aprovechar el cache de Docker.
COPY package*.json ./

# Instala TODAS las dependencias, incluyendo las de desarrollo como nodemon.
RUN npm install

# Copia el resto del código (aunque el volumen lo sobreescribirá, es buena práctica tenerlo).
COPY . .

# Expone el puerto.
EXPOSE 4000

